/**
 * RBAC Permission Definitions
 * All permissions are checked server-side. UI hiding is cosmetic only.
 * DENY BY DEFAULT — if permission not found, access is DENIED.
 */

export const PERMISSIONS = {
  // Document permissions
  DOCUMENT_READ: "document.read",
  DOCUMENT_CREATE: "document.create",
  DOCUMENT_UPDATE: "document.update",
  DOCUMENT_DELETE: "document.delete",
  DOCUMENT_PUBLISH: "document.publish",
  DOCUMENT_REINDEX: "document.reindex",

  // Knowledge permissions
  KNOWLEDGE_READ: "knowledge.read",
  KNOWLEDGE_CREATE: "knowledge.create",
  KNOWLEDGE_UPDATE: "knowledge.update",
  KNOWLEDGE_DELETE: "knowledge.delete",
  KNOWLEDGE_REVIEW: "knowledge.review",
  KNOWLEDGE_APPROVE: "knowledge.approve",
  KNOWLEDGE_PUBLISH: "knowledge.publish",

  // Experience permissions
  EXPERIENCE_READ: "experience.read",
  EXPERIENCE_CREATE: "experience.create",
  EXPERIENCE_UPDATE: "experience.update",
  EXPERIENCE_DELETE: "experience.delete",
  EXPERIENCE_SUBMIT: "experience.submit",
  EXPERIENCE_REVIEW: "experience.review",
  EXPERIENCE_APPROVE: "experience.approve",
  EXPERIENCE_PUBLISH: "experience.publish",

  // Chat permissions
  CHAT_USE: "chat.use",
  CHAT_VIEW_TRACE: "chat.view_trace",

  // Search permissions
  SEARCH_USE: "search.use",

  // Admin permissions
  ADMIN_ACCESS: "admin.access",
  ADMIN_SYSTEM: "admin.system",

  // Audit permissions
  AUDIT_READ: "audit.read",

  // User management
  USER_READ: "user.read",
  USER_CREATE: "user.create",
  USER_UPDATE: "user.update",
  USER_DELETE: "user.delete",
  USER_MANAGE: "user.manage",

  // Role management
  ROLE_READ: "role.read",
  ROLE_MANAGE: "role.manage",

  // Organization management
  ORG_READ: "org.read",
  ORG_MANAGE: "org.manage",

  // Department management
  DEPT_READ: "dept.read",
  DEPT_MANAGE: "dept.manage",

  // Backup & restore
  BACKUP_CREATE: "backup.create",
  BACKUP_RESTORE: "backup.restore",
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

/**
 * System roles and their default permissions
 * Roles: SUPER_ADMIN, ORG_ADMIN, DEPARTMENT_MANAGER,
 *        KNOWLEDGE_MANAGER, REVIEWER, EMPLOYEE, VIEWER
 */
export const ROLE_NAMES = {
  SUPER_ADMIN: "SUPER_ADMIN",
  ORG_ADMIN: "ORG_ADMIN",
  DEPARTMENT_MANAGER: "DEPARTMENT_MANAGER",
  KNOWLEDGE_MANAGER: "KNOWLEDGE_MANAGER",
  REVIEWER: "REVIEWER",
  EMPLOYEE: "EMPLOYEE",
  VIEWER: "VIEWER",
} as const;

export type RoleName = (typeof ROLE_NAMES)[keyof typeof ROLE_NAMES];

export const ROLE_DEFAULT_PERMISSIONS: Record<RoleName, Permission[]> = {
  SUPER_ADMIN: Object.values(PERMISSIONS),
  ORG_ADMIN: [
    PERMISSIONS.DOCUMENT_READ,
    PERMISSIONS.DOCUMENT_CREATE,
    PERMISSIONS.DOCUMENT_UPDATE,
    PERMISSIONS.DOCUMENT_DELETE,
    PERMISSIONS.DOCUMENT_PUBLISH,
    PERMISSIONS.DOCUMENT_REINDEX,
    PERMISSIONS.KNOWLEDGE_READ,
    PERMISSIONS.KNOWLEDGE_CREATE,
    PERMISSIONS.KNOWLEDGE_UPDATE,
    PERMISSIONS.KNOWLEDGE_DELETE,
    PERMISSIONS.KNOWLEDGE_REVIEW,
    PERMISSIONS.KNOWLEDGE_APPROVE,
    PERMISSIONS.KNOWLEDGE_PUBLISH,
    PERMISSIONS.EXPERIENCE_READ,
    PERMISSIONS.EXPERIENCE_CREATE,
    PERMISSIONS.EXPERIENCE_UPDATE,
    PERMISSIONS.EXPERIENCE_DELETE,
    PERMISSIONS.EXPERIENCE_REVIEW,
    PERMISSIONS.EXPERIENCE_APPROVE,
    PERMISSIONS.EXPERIENCE_PUBLISH,
    PERMISSIONS.CHAT_USE,
    PERMISSIONS.CHAT_VIEW_TRACE,
    PERMISSIONS.SEARCH_USE,
    PERMISSIONS.ADMIN_ACCESS,
    PERMISSIONS.AUDIT_READ,
    PERMISSIONS.USER_READ,
    PERMISSIONS.USER_CREATE,
    PERMISSIONS.USER_UPDATE,
    PERMISSIONS.USER_DELETE,
    PERMISSIONS.USER_MANAGE,
    PERMISSIONS.ROLE_READ,
    PERMISSIONS.ROLE_MANAGE,
    PERMISSIONS.ORG_READ,
    PERMISSIONS.DEPT_READ,
    PERMISSIONS.DEPT_MANAGE,
    PERMISSIONS.BACKUP_CREATE,
  ],
  DEPARTMENT_MANAGER: [
    PERMISSIONS.DOCUMENT_READ,
    PERMISSIONS.DOCUMENT_CREATE,
    PERMISSIONS.DOCUMENT_UPDATE,
    PERMISSIONS.KNOWLEDGE_READ,
    PERMISSIONS.KNOWLEDGE_CREATE,
    PERMISSIONS.KNOWLEDGE_UPDATE,
    PERMISSIONS.KNOWLEDGE_REVIEW,
    PERMISSIONS.KNOWLEDGE_APPROVE,
    PERMISSIONS.EXPERIENCE_READ,
    PERMISSIONS.EXPERIENCE_CREATE,
    PERMISSIONS.EXPERIENCE_UPDATE,
    PERMISSIONS.EXPERIENCE_REVIEW,
    PERMISSIONS.EXPERIENCE_APPROVE,
    PERMISSIONS.CHAT_USE,
    PERMISSIONS.SEARCH_USE,
    PERMISSIONS.USER_READ,
    PERMISSIONS.DEPT_READ,
    PERMISSIONS.ORG_READ,
  ],
  KNOWLEDGE_MANAGER: [
    PERMISSIONS.DOCUMENT_READ,
    PERMISSIONS.DOCUMENT_CREATE,
    PERMISSIONS.DOCUMENT_UPDATE,
    PERMISSIONS.DOCUMENT_PUBLISH,
    PERMISSIONS.KNOWLEDGE_READ,
    PERMISSIONS.KNOWLEDGE_CREATE,
    PERMISSIONS.KNOWLEDGE_UPDATE,
    PERMISSIONS.KNOWLEDGE_REVIEW,
    PERMISSIONS.KNOWLEDGE_APPROVE,
    PERMISSIONS.KNOWLEDGE_PUBLISH,
    PERMISSIONS.EXPERIENCE_READ,
    PERMISSIONS.EXPERIENCE_REVIEW,
    PERMISSIONS.EXPERIENCE_APPROVE,
    PERMISSIONS.CHAT_USE,
    PERMISSIONS.SEARCH_USE,
    PERMISSIONS.DEPT_READ,
    PERMISSIONS.ORG_READ,
  ],
  REVIEWER: [
    PERMISSIONS.DOCUMENT_READ,
    PERMISSIONS.KNOWLEDGE_READ,
    PERMISSIONS.KNOWLEDGE_REVIEW,
    PERMISSIONS.EXPERIENCE_READ,
    PERMISSIONS.EXPERIENCE_REVIEW,
    PERMISSIONS.CHAT_USE,
    PERMISSIONS.SEARCH_USE,
    PERMISSIONS.DEPT_READ,
    PERMISSIONS.ORG_READ,
  ],
  EMPLOYEE: [
    PERMISSIONS.DOCUMENT_READ,
    PERMISSIONS.KNOWLEDGE_READ,
    PERMISSIONS.EXPERIENCE_READ,
    PERMISSIONS.EXPERIENCE_CREATE,
    PERMISSIONS.EXPERIENCE_UPDATE,
    PERMISSIONS.EXPERIENCE_SUBMIT,
    PERMISSIONS.CHAT_USE,
    PERMISSIONS.SEARCH_USE,
    PERMISSIONS.DEPT_READ,
    PERMISSIONS.ORG_READ,
  ],
  VIEWER: [
    PERMISSIONS.DOCUMENT_READ,
    PERMISSIONS.KNOWLEDGE_READ,
    PERMISSIONS.EXPERIENCE_READ,
    PERMISSIONS.CHAT_USE,
    PERMISSIONS.SEARCH_USE,
    PERMISSIONS.DEPT_READ,
    PERMISSIONS.ORG_READ,
  ],
};
